name: uptodo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  image_picker: ^1.1.2 # Cho chọn/chụp ảnh
  path_provider: ^2.1.1  # Để lưu ảnh vào thư mục app
  easy_localization: ^3.0.5



  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.17.5
  # firebase_messaging: ^15.1.3
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "icon_launcher.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
